# Generated by Django 4.1.6 on 2023-06-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_participant_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile_image',
            field=models.ImageField(upload_to='profile-pics'),
        ),
    ]
