# Generated by Django 4.1.6 on 2023-06-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_participant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='profile_image',
            field=models.ImageField(upload_to='profile-pics/'),
        ),
    ]
