# Generated by Django 4.1.6 on 2023-06-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_participant_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='reference',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='registration_number',
            field=models.CharField(default=0, editable=False, max_length=9),
            preserve_default=False,
        ),
    ]
