# Generated by Django 4.1.6 on 2023-06-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_participant_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='reference',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
