# Generated by Django 4.1.6 on 2023-06-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_participant_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
