# Generated by Django 4.1.6 on 2023-06-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0007_delete_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profile-pics/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('registration_number', models.CharField(editable=False, max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=8)),
                ('category', models.CharField(max_length=100)),
                ('name_of_school', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_registered', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
