# Generated by Django 4.1.6 on 2023-06-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='reference',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registration_number',
            field=models.CharField(max_length=9),
        ),
    ]
